spring:
  application:
    name: springboot-zipkin-server
  cloud:
    config:
      uri: http://forsrc.local:12000/config
  boot:
    admin:
      url: http://forsrc.local:13000/admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://forsrc.local:11100/eureka/eureka

management:
  context-path: /mgmt
  security:
    enabled: false

server:
  port: 11110
  #context-path: /zipkin


